[package]
name = "chunks-fs"
version = "0.1.0"
authors = ["Christian Berg <berg.christian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = "2.5.2"
slog-term = "2.4.2"
slog-async = "2.3.0"